/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Guzman
 */
public class Inventario extends javax.swing.JPanel {

    public JTable getTablaInventario() {
        return TablaInventario;
    }

    public JButton getBtnconsultarInventario() {
        return btnconsultarInventario;
    }

    /**
     * Creates new form Muebles
     */
    public Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mueblespanel = new javax.swing.JTabbedPane();
        panelvendermuebles = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaInventario = new javax.swing.JTable();
        btnconsultarInventario = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 0));
        setLayout(null);

        mueblespanel.setBackground(new java.awt.Color(255, 255, 255));
        mueblespanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        panelvendermuebles.setBackground(new java.awt.Color(204, 204, 204));
        panelvendermuebles.setForeground(new java.awt.Color(204, 204, 0));

        TablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Nombre", "Cantidad", "Precio"
            }
        ));
        jScrollPane3.setViewportView(TablaInventario);

        btnconsultarInventario.setText("Consultar");

        javax.swing.GroupLayout panelvendermueblesLayout = new javax.swing.GroupLayout(panelvendermuebles);
        panelvendermuebles.setLayout(panelvendermueblesLayout);
        panelvendermueblesLayout.setHorizontalGroup(
            panelvendermueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelvendermueblesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelvendermueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnconsultarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        panelvendermueblesLayout.setVerticalGroup(
            panelvendermueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelvendermueblesLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnconsultarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        mueblespanel.addTab("Inventario", panelvendermuebles);

        add(mueblespanel);
        mueblespanel.setBounds(20, 10, 650, 400);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaInventario;
    private javax.swing.JButton btnconsultarInventario;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane mueblespanel;
    private javax.swing.JPanel panelvendermuebles;
    // End of variables declaration//GEN-END:variables
}
